server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/university_management_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    open-in-view: false


jwt:
  secret: sretnaersntaeirhtehdnrat23423enih
  expiration: 3600000
dean:
  default:
    eamil: dean@email.com
    password: dean




