server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/university_management_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    open-in-view: true
  security:
    user:
      name: user
      password: user
      roles: ROLE_ADMIN
